# Generated by Django 4.2.7 on 2023-11-17 18:26

from django.db import migrations, models
import myApp.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='organizationInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orgName', models.CharField(max_length=50, verbose_name='Organization Name')),
                ('orgEmail', models.EmailField(max_length=254, verbose_name='Organization Email')),
                ('orgContact', models.CharField(max_length=14, verbose_name='Organization Contact')),
                ('orgAddress', models.CharField(max_length=255, verbose_name='Organization Address')),
                ('adminName', models.CharField(max_length=50, verbose_name='Admin Name')),
                ('adminDesig', models.CharField(max_length=50, verbose_name='Admin Designation')),
                ('adminEmail', models.EmailField(max_length=254, verbose_name='Admin Email')),
                ('adminContact', models.CharField(max_length=14, verbose_name='Admin Contact')),
                ('xmlForm', models.FileField(upload_to=myApp.models.organizationInfoPath, verbose_name='XML Form')),
            ],
            options={
                'verbose_name_plural': 'Organization Information',
            },
        ),
    ]
